# Generated by Django 5.0.9 on 2024-09-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_init_email_customer_init_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='init_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
