# Generated by Django 5.0.9 on 2024-09-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('basic', 'Basic Plan'), ('advanced', 'Advanced Plan'), ('pro', 'Pro Plan')],
            },
        ),
    ]
