# Generated by Django 5.0.9 on 2024-09-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='group',
            new_name='groups',
        ),
    ]
