# Generated by Django 5.0.9 on 2024-09-07 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_usersubscriptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubscriptions',
            new_name='UserSubscription',
        ),
    ]
