# Generated by Django 5.0.9 on 2024-09-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_alter_subscriptionprice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['order', 'featured', '-updated'], 'permissions': [('basic', 'Basic Plan'), ('advanced', 'Advanced Plan'), ('pro', 'Pro Plan')]},
        ),
    ]
