name: Django basics test env variables

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  django-test:
    runs-on: ubuntu-latest
    env:
      DJANGO_DEBUG: 0
      # DJANGO_SECRET_KEY: changeme
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup Django secret key
        run: |
          GEN_KEY=$(openssl rand -base64 64)
          echo "DJANGO_SECRET_KEY=$GEN_KEY" >> $GITHUB_ENV
      - name: Install requirements
        run: |
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt
      - name: Django test
        working-directory: ./src
        run: |
          python manage.py test
